### ISSUE TITLE
Dependabot treats git+https dependencies like git dependencies/breaks deployments

### ISSUE THREAD

**Issue by al** [al/lionels-legacy#41]
## Summary

Whenever dependabot updates pnpm-lock.yaml it seems to change git+https dependencies to git dependencies, and thus break deployments e.g. https://github.com/al/lionels-legacy/commit/06874e6a196ddb88283a29927c33ce8c64107bfd#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL1200-L1201

## How to Reproduce?

1. Review any dependabout PR that updates packages.
1. Note that it changes the details of the branch-name-lint dependency, e.g. https://github.com/al/lionels-legacy/commit/06874e6a196ddb88283a29927c33ce8c64107bfd#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL1200-L1201

## Expected Behaviour

It should not unilaterally change git dependencies in pnpm-lock.yaml.

## Other Details

Not clear if this is a PNPM or a dependabot issue.

**Related**

- https://github.com/al/lionels-legacy/actions/runs/10367636322
- #33
- https://github.com/dependabot/dependabot-core/issues/10124

### Update

This is now happening locally too, so it's probably a change in PNPM behaviour. Can be worked around by specifying the dependency as a tarball URL rather than git+https.

**Comment by GabrielGil** [comment]
PNPM issue, if you ask me. :)
